### ISSUE TITLE
小米 14 Pro 的数据结构有点问题

### ISSUE THREAD

**Issue by tofarfar** [HegeKen/HyperData#1]
Hi，从 B 站无意看到你的一个视频，找到来 Github，发现这个宝藏仓库，感谢你的付出和分享！

发现一个小问题，小米 14 Pro 的[数据结构](https://github.com/HegeKen/HyperData/blob/5f5832fdc548973fe23d33983818381aac30e8d9/devices/shennong.json#L219)有点问题，导致它的电信定制版在网站[没有显示](https://www.hyperos.fans/zh/devices/shennong)出最新的版本。

再次感谢！

**Comment by HegeKen** [comment]
感谢提醒，已经调整好了。非常感谢！
