### ISSUE TITLE
K40 游戏增强版出内测正式版啦

### ISSUE THREAD

**Issue by tofarfar** [HegeKen/HyperData#10]
Hi，K40 游戏增强版出内测正式版啦，想问下通常发版后这个仓库多久可以收集到呢？感谢！

![IMG_2184 PNG-14753](https://github.com/HegeKen/HyperData/assets/6022398/eeee0e14-1025-4562-92f9-c57453dfe5e1)

**Comment by HegeKen** [comment]
是的，已经合入更新，早上有点事，晚了点。
