### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by SupremeOwi** [HegeKen/HyperData#14]
What is the difference between "**HyperOS Stable**" and "**HyperOS China Telecom Carrier Edition**" ? I noticed that the download URL for Recovery is the same, with no apparent difference.

### Example
• HyperOS Stable: https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS1.0.12.0.UMBCNXM/miui_NUWA_OS1.0.12.0.UMBCNXM_230e1e553b_14.0.zip

• HyperOS China Telecom Carrier Edition: https://bkt-sgp-miui-ota-update-alisgp.oss-ap-southeast-1.aliyuncs.com/OS1.0.12.0.UMBCNXM/miui_NUWA_OS1.0.12.0.UMBCNXM_230e1e553b_14.0.zip

![Screenshot](https://github.com/user-attachments/assets/2015e63d-6deb-4a45-a43a-a9638c68bfd0)

**Comment by HegeKen** [comment]
differences actually are only in the fastboot files, I thinked about merging these into Stable one, but hadn't try to do it at the moment.

**Comment by HegeKen** [comment]
differences actually are only in the fastboot files, I thought about merging these into Stable one, but hadn't try to do it at the moment.

**Comment by HegeKen** [comment]
It took me merely whole day to merge it, and good neeeews, it has been done.
