### ISSUE TITLE
小米 Civi 3 这款机型缺少下载链接？

### ISSUE THREAD

**Issue by tofarfar** [HegeKen/HyperData#2]
Hi，今天留意到多了 [Civi 3 的数据](https://github.com/HegeKen/HyperData/blob/75d7ad18deb9a7b4076dd101c8b10dd82d16740b/devices/yuechu.json#L34)，但是 fastbook 和 recovery 字段都是空的，这是为啥啊？我不会 python，所以没有尝试看源码定位问题。

我用这个仓库的[数据](https://github.com/HegeKen/HyperData/tree/main/devices)写了一个微信小程序，不知道合不合适😄️：

![gh_2b14ca3db6c7_258](https://github.com/HegeKen/HyperData/assets/6022398/0abce66c-7bd0-4821-ad78-f3d90e8c90b2)

提一个小需求，如果可以增加各 rom 的发布时间就好了！

**Comment by HegeKen** [comment]
当时是Civi3 迪士尼定制版确定会近期发了，所以提前准备的数据结构，果然第二天旧看到链接了。

**Comment by HegeKen** [comment]
时间这个我补一下，稍等一下

**Comment by HegeKen** [comment]
发布时间已经补充完了。
