### ISSUE TITLE
小米 14 Pro 日期格式有误

### ISSUE THREAD

**Issue by tofarfar** [HegeKen/HyperData#3]
Hi，感谢火速加了发布日期！发现一个小小问题，小米 14 Pro 一个版本的[日期格式有误](https://github.com/HegeKen/HyperData/blob/c45d54df3a71988e1f903f55a3605562795bce8d/devices/shennong.json#L96)。所有版本都看了一次，暂时只发现这一个错误，感谢！

**Comment by HegeKen** [comment]
感谢指正，已在最新提交中修正。
