### ISSUE TITLE
socrates、ingres 最新开发版固件链接有误

### ISSUE THREAD

**Issue by tofarfar** [HegeKen/HyperData#6]
[ingres](https://github.com/HegeKen/HyperData/blob/2c5c762490729c507067a2edc6a55ee3bc1563ff/devices/ingres.json#L29C10-L29C10)（红米K50 电竞版 / POCO F4 GT）、[socrates](https://github.com/HegeKen/HyperData/blob/2c5c762490729c507067a2edc6a55ee3bc1563ff/devices/socrates.json#L29C11-L29C11)（红米K60 Pro） 最新开发版似乎错误地写成了 mondrian（红米K60 / POCO F5 Pro）、matisse（红米K50 Pro） 的固件？

**Comment by HegeKen** [comment]
感谢提醒，该错误已经订正。
