### ISSUE TITLE
红米平板 SE 的名称有误

### ISSUE THREAD

**Issue by tofarfar** [HegeKen/HyperData#8]
Hi，发现了一个小问题，[这里的](https://github.com/HegeKen/HyperData/blob/4f453809a48cbe5c86b4eaad90356a8f6969aaae/devices.json#L531) 名称似乎应该是红米 Pad SE？但写成了红米 Pad

另外网站的 xun 图片没有显示：
<img width="588" alt="截屏2024-02-24 18 57 44" src="https://github.com/HegeKen/HyperData/assets/6022398/a722d90b-8b7f-43f6-86cc-5eb8fc1cacd2">

**Comment by HegeKen** [comment]
感谢订正，已在最新提交中更正。
