### ISSUE TITLE
[勘误]主页内将aurora误写为aurota

### ISSUE THREAD

**Issue by tosasitill** [HegeKen/HyperData#9]
<img width="360" alt="图片" src="https://github.com/HegeKen/HyperData/assets/66861785/2526db22-a021-4dae-8e4f-9d5cb32a4134">
<img width="441" alt="图片" src="https://github.com/HegeKen/HyperData/assets/66861785/821db703-8411-45d5-bdac-1de38cdb4994">
导致跳转错误 手动将地址栏内的aurota改为aurora即可正常访问

**Comment by HegeKen** [comment]
感谢指正，该问题已在罪行提交中更正。
